on:
  pull_request_target:
    types: [opened]

jobs:
  issue_labeler:
    if: github.repository == 'azerothcore/GitHub-Actions'
    runs-on: ubuntu-latest
    name: PR Labeler
    steps:
    - name: PR Labeler
      id: issue-labeler
      uses: azerothcore/GitHub-Actions@core-labeler-1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
